import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import { analyzeRepository } from "../src/analysis.js";
import {
  isSupportedSourcePath,
  wholeFileProtectionReason,
} from "../src/file-policy.js";

function git(root: string, args: string[]): string {
  return execFileSync("git", args, { cwd: root, encoding: "utf8" });
}

test("source path policy supports the TypeScript family only", () => {
  for (const path of ["src/a.ts", "src/a.tsx", "src/a.mts", "src/a.cts"]) {
    assert.equal(isSupportedSourcePath(path), true, path);
  }

  for (const path of [
    "src/a.js",
    "src/a.jsx",
    "src/a.d.ts",
    "src/a.d.mts",
    "src/a.d.cts",
    "src/a.generated.ts",
    "vendor/a.ts",
    "third_party/a.ts",
    "migrations/001.ts",
    "__snapshots__/a.ts",
  ]) {
    assert.equal(isSupportedSourcePath(path), false, path);
  }
});

test("generated headers protect the whole file without matching ordinary strings", () => {
  const generatedHeaders = [
    "// @generated\nexport const value = 1;\n",
    "// <auto-generated />\nexport const value = 1;\n",
    "/*\n * This file is generated. Do not edit manually.\n */\nexport const value = 1;\n",
    "// Code generated by a schema tool. DO NOT EDIT.\nexport const value = 1;\n",
  ];

  for (const source of generatedHeaders) {
    assert.match(wholeFileProtectionReason("src/output.ts", source) ?? "", /Generated/);
  }

  const ordinary = [
    'const instruction = "// do not edit this example";',
    "// Keep this value stable for compatibility.",
    "export const value = 1;",
    "",
  ].join("\n");
  assert.equal(wholeFileProtectionReason("src/source.ts", ordinary), undefined);
});

test("a generated header suppresses every finding in the changed file", () => {
  const root = mkdtempSync(join(tmpdir(), "repofit-generated-file-test-"));
  try {
    git(root, ["init", "-q"]);
    git(root, ["config", "user.email", "repofit@example.invalid"]);
    git(root, ["config", "user.name", "RepoFit Test"]);
    mkdirSync(join(root, "src"));
    const path = join(root, "src", "generated.ts");
    const baseline = [
      "// Code generated by SchemaTool. DO NOT EDIT.",
      "export function answer(): number {",
      "  return 42;",
      "}",
      "",
    ].join("\n");
    writeFileSync(path, baseline);
    git(root, ["add", "."]);
    git(root, ["commit", "-qm", "baseline"]);
    writeFileSync(
      path,
      baseline.replace("  return 42;", "  // Main Logic\n  return 42;"),
    );

    const report = analyzeRepository(root, { kind: "worktree" });
    assert.equal(report.summary.analyzedFileCount, 0);
    assert.equal(report.findings.length, 0);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("MTS and CTS files use the same changed-comment analysis contract", () => {
  const root = mkdtempSync(join(tmpdir(), "repofit-typescript-modules-test-"));
  try {
    git(root, ["init", "-q"]);
    git(root, ["config", "user.email", "repofit@example.invalid"]);
    git(root, ["config", "user.name", "RepoFit Test"]);
    mkdirSync(join(root, "src"));
    const baseline = [
      "export function answer(): number {",
      "  return 42;",
      "}",
      "",
    ].join("\n");
    for (const filename of ["module.mts", "common.cts"]) {
      writeFileSync(join(root, "src", filename), baseline);
    }
    git(root, ["add", "."]);
    git(root, ["commit", "-qm", "baseline"]);
    for (const filename of ["module.mts", "common.cts"]) {
      writeFileSync(
        join(root, "src", filename),
        baseline.replace("  return 42;", "  // Step 1\n  return 42;"),
      );
    }

    const report = analyzeRepository(root, { kind: "worktree" });
    assert.equal(report.summary.analyzedFileCount, 2);
    assert.equal(report.summary.removeSafeCount, 2);
    assert.deepEqual(
      report.findings.map((finding) => finding.relativePath).sort(),
      ["src/common.cts", "src/module.mts"],
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
