const SOURCE_EXTENSION_PATTERN = /\.(?:[cm]?ts|tsx)$/i;
const DECLARATION_FILE_PATTERN = /\.d\.(?:ts|mts|cts)$/i;
const GENERATED_FILENAME_PATTERN = /(?:\.generated|\.gen|\.min)\.(?:[cm]?ts|tsx)$/i;
const PROTECTED_DIRECTORY_PATTERN =
  /(^|\/)(?:node_modules|vendors?|third[_-]party|dist|build|coverage|generated|__generated__|fixtures?|__fixtures__|migrations?|__migrations__|snapshots?|__snapshots__)(?:\/|$)/i;
const COMMENT_LINE_PATTERN = /^(?:\/\/|\/\*|\*)/;
const GENERATED_HEADER_MARKER_PATTERN =
  /(?:@generated\b|<auto-generated\b|auto[- ]generated\b|generated\s+(?:file|code)\b|this\s+file\s+(?:is|was)\s+generated\b|code\s+generated\b.*\bdo\s+not\s+edit\b|do\s+not\s+edit(?:\s+manually)?\b)/i;

export function isSupportedSourcePath(relativePath: string): boolean {
  if (
    !SOURCE_EXTENSION_PATTERN.test(relativePath) ||
    DECLARATION_FILE_PATTERN.test(relativePath)
  ) {
    return false;
  }

  return (
    !PROTECTED_DIRECTORY_PATTERN.test(relativePath) &&
    !GENERATED_FILENAME_PATTERN.test(relativePath)
  );
}

export function wholeFileProtectionReason(
  relativePath: string,
  content: string,
): string | undefined {
  if (!isSupportedSourcePath(relativePath)) {
    return "Unsupported, declared, generated, vendored, fixture, migration, or snapshot path.";
  }

  const generatedHeader = content
    .slice(0, 4096)
    .split(/\r?\n/, 20)
    .some((line) => {
      const trimmed = line.trim();
      return (
        COMMENT_LINE_PATTERN.test(trimmed) &&
        GENERATED_HEADER_MARKER_PATTERN.test(trimmed)
      );
    });
  if (generatedHeader) {
    return "Generated or do-not-edit file header.";
  }

  return undefined;
}
