import { sha256 } from "./hash.js";
import type { SourceComment } from "./model.js";

export const RATIONALE_PROTECTION_REASON =
  "Possible rationale, constraint, compatibility, or invariant.";
export const LEADING_COMMENT_PROTECTION_REASON =
  "Leading file comments are protected as possible headers or module documentation.";

const STEP_NARRATION_PATTERN = /^(?:(?:step|phase|part)\s*(?:\d+|one|two|three|four|five)|步骤\s*[一二三四五六七八九十\d]+)\s*[:：.\-]\s*(\S.*)$/i;

const LEGAL_PATTERN = /\b(?:copyright|spdx|license|licensed|all rights reserved|author|attribution)\b|(?:版权|许可证|作者|归属)/i;
const TOOL_PATTERN = /(?:repofit-ignore-next-line|eslint|prettier|biome-ignore|oxlint|deno-lint|nosonar|noqa|@ts-(?:ignore|expect-error|nocheck|check)|@[A-Za-z][\w-]*|istanbul|\bc8\b|sourceMappingURL|webpack|rollup|vite|#__PURE__|sourcemap|coverage|swiftlint|swiftformat|sourcery|region|endregion|falls?\s+through)/i;
const LANGUAGE_TOOL_PATTERN = /(?:\b(?:go:build|go:generate|\+build|type:\s*ignore|pyright|mypy|ruff|pylint|clippy|rustfmt|noinspection|nolint|clang-format|phpstan|psalm|rubocop|dart\s+format|shellcheck|sqlfluff|svelte-ignore|coding[:=])\b|\bignore_for_file\b|\bignore:\s*[a-z])/i;
const GENERATED_PATTERN = /\b(?:generated|do not edit|autogenerated|auto-generated|vendor|minified)\b|(?:自动生成|请勿编辑|不要编辑)/i;
const TRACKING_PATTERN = /\b(?:TODO|FIXME|HACK|XXX)\b|(?:#[0-9]{2,}|[A-Z][A-Z0-9]+-[0-9]+)|https?:\/\//i;
const CONSTRAINT_PATTERN = /\b(?:because|must|never|only|workaround|invariant|compat(?:ibility)?|backward|security|privacy|permission|thread|lock|atomic|lifecycle|ownership|unsafe|ffi|schema|timezone|precision|encoding|migration|unit|protocol|regex|intentional(?:ly)?|edge case|according to|so|in order to|to avoid|without|preserve|prevent)\b|(?:因为|由于|必须|不得|仅限|绕过|不变量|兼容|安全|隐私|权限|并发|锁|原子|生命周期|精度|时区|编码|迁移|协议|正则|故意|边界条件|根据|以便|为了避免|避免|保留|防止)/i;
const VALUE_PATTERN = /(?:\b\d+(?:\.\d+)+(?:ms|s|px|kb|mb|gb|hz|%|°)?\b|\b\d+(?:ms|s|px|kb|mb|gb|hz|%|°)\b|\b\d+\s+(?:times?|bytes?|seconds?|minutes?|hours?|days?|items?|rows?|columns?|bits?)\b|\d+\s*(?:次|字节|秒|分钟|小时|天|行|列|位)|v\d+(?:\.\d+)+|RFC\s*\d+)/i;
const COMMENTED_CODE_PATTERN = /(?:=>|===|!==|==|!=|&&|\|\||\{\s*$|\}\s*$|;\s*$|\b(?:const|let|var|function|class|import|export)\s+[A-Za-z_$])/;

export function normalizeComment(value: string): string {
  return value
    .normalize("NFKC")
    .toLowerCase()
    .replace(/[`'"*_#]/g, "")
    .replace(/[\s\-=:;,.!?()[\]{}<>/\\|]+/g, " ")
    .trim();
}

export function commentLanguage(value: string): "zh" | "en" | "mixed" | "unknown" {
  const hasChinese = /[\u3400-\u9fff]/u.test(value);
  const hasEnglish = /[a-z]/i.test(value);
  if (hasChinese && hasEnglish) return "mixed";
  if (hasChinese) return "zh";
  if (hasEnglish) return "en";
  return "unknown";
}

export function lineCommentPrefix(raw: string): string {
  return /^(?:\/\/[/!]?|#|--)/u.exec(raw)?.[0] ?? "//";
}

export function stepNarrationReplacement(
  comment: Pick<SourceComment, "content" | "raw">,
): string | undefined {
  const match = STEP_NARRATION_PATTERN.exec(comment.content.trim());
  const remainder = match?.[1]?.trim();
  if (!remainder) {
    return undefined;
  }
  const first = remainder[0];
  const normalized = first && /[a-z]/.test(first) ? `${first.toUpperCase()}${remainder.slice(1)}` : remainder;
  return `${lineCommentPrefix(comment.raw)} ${normalized}`;
}

export function protectedReason(
  comment: SourceComment,
  extraPhrases: readonly string[] = [],
): string | undefined {
  const value = comment.content;

  const normalizedValue = normalizeComment(value);
  const configuredPhrase = extraPhrases.find((phrase) => {
    const normalizedPhrase = normalizeComment(phrase);
    return normalizedPhrase.length > 0 && normalizedValue.includes(normalizedPhrase);
  });
  if (configuredPhrase !== undefined) {
    return `Repository-configured protected phrase: ${configuredPhrase}`;
  }

  if (comment.kind !== "line") {
    return "Block, markup, and documentation comments are protected from automatic changes.";
  }
  if (comment.raw.startsWith("///")) {
    return "Documentation comments are protected.";
  }
  if (comment.leadingFileComment) {
    return LEADING_COMMENT_PROTECTION_REASON;
  }
  if (LEGAL_PATTERN.test(value)) {
    return "Legal, authorship, or attribution comment.";
  }
  if (TOOL_PATTERN.test(value) || LANGUAGE_TOOL_PATTERN.test(value)) {
    return "Tool, compiler, formatter, or coverage directive.";
  }
  if (GENERATED_PATTERN.test(value)) {
    return "Generated-file or do-not-edit marker.";
  }
  if (TRACKING_PATTERN.test(value)) {
    return "Tracked TODO, issue, URL, or maintenance marker.";
  }
  if (CONSTRAINT_PATTERN.test(value)) {
    return RATIONALE_PROTECTION_REASON;
  }
  if (VALUE_PATTERN.test(value)) {
    return "Contains a value, unit, version, or standards reference.";
  }
  if (COMMENTED_CODE_PATTERN.test(value)) {
    return "Possible commented-out code; requires human review.";
  }

  return undefined;
}

export function protectedCommentHash(
  comments: SourceComment[],
  extraPhrases: readonly string[] = [],
): string {
  const protectedComments = comments
    .flatMap((comment) => {
      const reason = protectedReason(comment, extraPhrases);
      if (reason === undefined) {
        return [];
      }
      if (
        reason === RATIONALE_PROTECTION_REASON ||
        reason === LEADING_COMMENT_PROTECTION_REASON
      ) {
        return [stepNarrationReplacement(comment) ?? comment.raw];
      }
      return [comment.raw];
    });
  return sha256(JSON.stringify(protectedComments));
}
